linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gocyclo
    - godox
    - golint
    - ifshort
    - interfacer
    - ireturn # reports generic types as interfaces
    - lll
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - predeclared
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
run:
  skip-files:
    - _test.go$
